comodo/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views


from . import views

app_name = 'comodo'



urlpatterns = [
    url(r'^$',views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^post_edit/(?P<pk>\d+)/', views.EditPostView.as_view(), name='post_edit'),
    url(r'^post_create/$', views.CreatePostView.as_view(), name='post_create'),
    url(r'^register/$', views.register, name='register'),
    url(r'^accounts/login/$',
    auth_views.login,
    {'template_name': 'kayit.html'},
    name='auth_login'),
    url(r'^logout/$',
    auth_views.logout,
    {'template_name': 'registration/logout.html'},
    name='auth_logout'),
    url(r'^password/change/$',
    auth_views.password_change,
    name='auth_password_change'),
url(r'^password/change/done/$',
    auth_views.password_change_done,
    name='password_change_done'),
url(r'^password/reset/$',
    auth_views.password_reset,
    name='auth_password_reset'),
url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    auth_views.password_reset_confirm,
    name='auth_password_reset_confirm'),
url(r'^password/reset/complete/$',
    auth_views.password_reset_complete,
    name='auth_password_reset_complete'),
url(r'^password/reset/done/$',
    auth_views.password_reset_done,
    name='password_reset_done'),

]

portal/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^webportal/', include('webportal.urls')),
]

sosyal/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from comodo.models import MyUser




class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = MyUser
        fields = ('username', 'email')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = MyUser.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'djr', UserViewSet)
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comodo/', include('comodo.urls', namespace='comodo')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/',include(router.urls, namespace='ruls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}"/>
	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

    <title>{% block title %}User test{% endblock %}</title>
</head>

{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#	<meta charset="utf-8">#}
{#	<meta http-equiv="X-UA-Compatible" content="IE=edge">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#	<title></title>#}
{#	<link rel="stylesheet" type="text/css" href="../static/css/custom.css">#}
{#	<link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">#}
{#	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">#}
{#	<script src="../static/js/jquery.js"></script>#}
{#	<script src="../static/js/bootstrap.min.js"></script>#}
{#</head>#}

<body>

	<!-- Header Bölümü -->
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Yardım Sitesi</a>
	    </div>
	    <div class="collapse navbar-collapse" id="myNavbar">
	      	<ul class="nav navbar-nav navbar-right">
       			<li class="dropdown">
			        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> &nbsp;Kullanici Adi <span class="caret"></span></a>
			        <ul class="dropdown-menu">
				        <li><a href="profilim.html">Profilim</a></li>

				        <li role="separator" class="divider"></li>
				        <li><a href="#">Çıkış</a></li>
			        </ul>
			    </li>
     		</ul>
		</div>
	  </div>
	</nav>

{#    <div id="header">#}
{#    {% block header %}#}
{#    <a href="{% url 'comodo:index' %}">{% trans "Home" %}</a> |#}
{##}
{#    {% if user.is_authenticated %}#}
{#        {% trans "Logged in" %}: {{ user.username }}#}
{#        (<a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a> | #}
{#        <a href="{% url 'auth_password_change' %}">{% trans "Change password" %}</a>)#}
{#    {% else %}#}
{#       <a href="{% url 'auth_login' %}">{% trans "Log in" %}</a>#}
{#    {% endif %}#}
{#    <hr />#}
{#    {% endblock %}#}
{#    </div>#}


    	<!-- main tasarım -->
	<div class="container-fluid">
		<div class="col-md-8">
			<div class="jumbotron">
				<button type="button" class="btn btn-success btn-lg btn-block" data-toggle="modal" data-target="#malzemelerim">Malzemelerim</button>
				<button type="button" class="btn btn-info btn-lg btn-block" data-toggle="modal" data-target="#malzeme_ekle">Malzeme Ekle</button><br>

					<div id="malzemelerim" class="modal fade" role="dialog">
					  <div class="modal-dialog">

					    <!-- Modal content-->
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal">&times;</button>
					        <h4 class="modal-title"><b>Malzemelerim</b></h4>
					      </div>
					      <div class="modal-body">
					        <p>Some text in the modal.</p>
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-default" data-dismiss="modal">Kapat</button>
					      </div>
					    </div>

					  </div>
					</div>

					<div id="malzeme_ekle" class="modal fade" role="dialog">
					  <div class="modal-dialog">

					    <!-- Modal content-->
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal">&times;</button>
					        <h4 class="modal-title"><b>Malzeme Ekle</b></h4>
					      </div>
					      <div class="modal-body">
					      <form>
					      <label for="exampleInputEmail1">Yardım Malzemesi Başlığı:</label>
					      <input type="text" class="form-control">
					       <label for="exampleInputEmail1">Yardım Malzemesi Hakkında Bilgiler:</label>
					      	<textarea class="form-control" rows="3"></textarea><br>

							    <label for="exampleInputFile">Resim Ekle</label>
							    <input type="file" id="exampleInputFile">
							    <p class="help-block">Malzeme Resiminizi Ekleyiniz.</p>

					      </div>
					      <div class="modal-footer">
					        <button type="submit" class="btn btn-default" >Kaydet</button>
					        </form>
					        <button type="button" class="btn btn-default" data-dismiss="modal">İptal</button>
					      </div>
					    </div>

					  </div>
					</div>

					<div class="row">
                        {% block content %}{% endblock %}
					</div>

			</div>
		</div>

{#    <div id="footer">#}
{#    {% block footer %}#}
{#        <hr />#}
{#    {% endblock %}#}
{#    </div>#}
    <div class="col-md-4">
			<div class="jumbotron">
				<div class="input-group input-group-lg">
			    <h4><b> <i class="fa fa-users" style="color: #4097C1;"></i>
			 		Yardıma Muhtaç Kişiler</b></h4><hr>
				</div>

				<script type="text/javascript">
					var i=0;
					for (var i = 0; i < 15; i++) {
						 document.write("<a href='#' data-toggle='tooltip' data-placement='left' title='Buraya Açıklama Yazısı Eklenecektir.!'><i class='fa fa-user' style='color: #5C9433;'></i>&nbsp;Yardıma Muhtaç Kişi<br></a><hr>");
					}
				</script>
			</div>
		</div>
        <br>
    <div>

	</div>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});
</script>


</body>
</html>
{#</body>#}
{##}
{#</html>#}

templates/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
    {% if user.is_authenticated and user.user_status == 1 %}

    <div class="col-sm-8">
        <h1>{{ post.message }}</h1>
        <br>
    <p>{% trans "Edit Post" %}? <a href="{% url 'comodo:post_edit' post.id %}">{% trans "Edit" %}</a>!</p>
    </div>
        {% else %}
        <p>Bu alani gorme yetkiniz yok...</p>
    {% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

    {% for post in postList %}
        {#        <a href="{% url 'comodo:detail' post.id %}">{{ post.title }}</a></br></br>#}
        {% if post.is_accomplished %}

        <div class="col-md-4">
            <a href="{% url 'comodo:detail' post.id %}" class="thumbnail" data-toggle='tooltip' data-placement='bottom'
               title='Buraya Açıklama Yazısı Eklenecektir.!'>

                <img src="http://lorempixel.com/image_output/abstract-q-c-640-480-8.jpg" alt="Pulpit Rock"
                     style="width:230px;height:230px">
                <p>{{ post.title }}</p>
            </a>
        </div>
       {% endif %}

    {% endfor %}

    {#    {% if poll_list %}#}
    {#<ul>#}
    {#    {% for poll in poll_list %}#}
    {#    <li><a href="{% url 'polls:poll' poll.id %}">{{ poll.p_date }}</a></li>#}
    {#        <p>{{ poll.p_content }}</p>#}
    {#    </li>#}
    {#    {% endfor %}#}
    {#</ul>#}

    {% if is_paginated %}
        {#    <div class="pagination">#}
        {#        <span class="page-links">#}
        {#            {% if page_obj.has_previous %}#}
        {#            <a href="?page={{ page_obj.previous_page_number }}">previous</a>#}
        {#            {% endif %}#}
        {#            <span class="page-current">#}
        {#                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}#}
        {#            </span>#}
        {#            {% if page_obj.has_next %}#}
        {#            <a href="?page={{ page_obj.next_page_number }}">next</a>#}
        {#            {% endif %}#}
        {#        </span>#}
        {#    </div>#}
        <nav>
            <ul class="pagination">
                <li>
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span
                                aria-hidden="true">&raquo;</span></a>
                    {% endif %}
                    </a>
                </li>
                {% for pages in page_numbers %}
                    <li><a href="?page={{ pages }}">{{ pages }}</a></li>
                {% endfor %}
                <li>
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span
                                aria-hidden="true">&raquo;</span></a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    {% endif %}


    {##}
    {#{% else %}#}
    {#    <p>No polls.</p>#}
    {#{% endif %}#}

{% endblock %}

templates/kayit.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/custom_kayit.css' %} ">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'comodo:register' %}">Yardım Sitesi</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <form class="navbar-form navbar-right" method="post" action="{% url 'auth_login' %}">
                {% csrf_token %}
                <input type="email" name="username" placeholder="Email Adresiniz" class="form-control" required>
                <input type="password" name="password" placeholder="Password" class="form-control" required>
                <input type="submit" value="Giriş Yap" class="btn btn-success">
            </form>
        </div>
    </div>
</nav>
    <div class="container margintop">
        <div class="col-md-5 myjumbotron">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="username" class="form-control" placeholder="Kullanici Adi"
                           style="text-align: center;"><br>
                    <select class="form-control" id="sel2" name="city" style="text-align: center;">
                        <option value="1">Adana</option>
                        <option value="2">Adıyaman</option>
                        <option value="3">Afyonkarahisar</option>
                        <option value="4">Ağrı</option>
                        <option value="5">Amasya</option>
                        <option value="6">Ankara</option>
                        <option value="7">Antalya</option>
                        <option value="8">Artvin</option>
                        <option value="9">Aydın</option>
                        <option value="10">Balıkesir</option>
                        <option value="11">Bilecik</option>
                        <option value="12">Bingöl</option>
                        <option value="13">Bitlis</option>
                        <option value="14">Bolu</option>
                        <option value="15">Burdur</option>
                        <option value="16">Bursa</option>
                        <option value="17">Çanakkale</option>
                        <option value="18">Çankırı</option>
                        <option value="19">Çorum</option>
                        <option value="20">Denizli</option>
                        <option value="21">Diyarbakır</option>
                        <option value="22">Edirne</option>
                        <option value="23">Elazığ</option>
                        <option value="24">Erzincan</option>
                        <option value="25">Erzurum</option>
                        <option value="26">Eskişehir</option>
                        <option value="27">Gaziantep</option>
                        <option value="28">Giresun</option>
                        <option value="29">Gümüşhane</option>
                        <option value="30">Hakkâri</option>
                        <option value="31">Hatay</option>
                        <option value="32">Isparta</option>
                        <option value="33">Mersin</option>
                        <option value="34">İstanbul</option>
                        <option value="35">İzmir</option>
                        <option value="36">Kars</option>
                        <option value="37">Kastamonu</option>
                        <option value="38">Kayseri</option>
                        <option value="39">Kırklareli</option>
                        <option value="40">Kırşehir</option>
                        <option value="41">Kocaeli</option>
                        <option value="42">Konya</option>
                        <option value="43">Kütahya</option>
                        <option value="44">Malatya</option>
                        <option value="45">Manisa</option>
                        <option value="46">Kahramanmaraş</option>
                        <option value="47">Mardin</option>
                        <option value="48">Muğla</option>
                        <option value="49">Muş</option>
                        <option value="50">Nevşehir</option>
                        <option value="51">Niğde</option>
                        <option value="52">Ordu</option>
                        <option value="53">Rize</option>
                        <option value="54">Sakarya</option>
                        <option value="55">Samsun</option>
                        <option value="56">Siirt</option>
                        <option value="57">Sinop</option>
                        <option value="58">Sivas</option>
                        <option value="59">Tekirdağ</option>
                        <option value="60">Tokat</option>
                        <option value="61">Trabzon</option>
                        <option value="62">Tunceli</option>
                        <option value="63">Şanlıurfa</option>
                        <option value="64">Uşak</option>
                        <option value="65">Van</option>
                        <option value="66">Yozgat</option>
                        <option value="67">Zonguldak</option>
                        <option value="68">Aksaray</option>
                        <option value="69">Bayburt</option>
                        <option value="70">Karaman</option>
                        <option value="71">Kırıkkale</option>
                        <option value="72">Batman</option>
                        <option value="73">Şırnak</option>
                        <option value="74">Bartın</option>
                        <option value="75">Ardahan</option>
                        <option value="76">Iğdır</option>
                        <option value="77">Yalova</option>
                        <option value="78">Karabük</option>
                        <option value="79">Kilis</option>
                        <option value="80">Osmaniye</option>
                        <option value="81">Düzce</option>
                    </select><br>
                    <input type="email" name="email" class="form-control" placeholder="Email "
                           style="text-align: center;"><br>
                    <input type="password" name="password1" class="form-control" placeholder="Password"
                           style="text-align: center;"><br>
                    <input type="password" name="password2" class="form-control" placeholder="Confirm Password"
                           style="text-align: center;"><br>
                    <label class="radio-inline boy"><input type="radio" value="1" name="user_status">Yardım Gönüllüsüyüm</label>
                    <label class="radio-inline boy"><input type="radio" value="2" name="user_status">İhtiyaç
                        Sahibiyim</label><br>
                    <hr>
                    <input type="submit" value="Kayit Ol" class="btn btn-primary btn-block"/>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

templates/main_yardim_alan.html
<!-- Yardım Gönüllüsü main sayfasıdır-->

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link rel="stylesheet" type="text/css" href="../static/css/custom.css">
	<link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
	<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
	<script src="../static/js/jquery.js"></script>
	<script src="../static/js/bootstrap.min.js"></script>
</head>
<body>
	<!-- Header Bölümü -->
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span> 
	      </button>
	      <a class="navbar-brand" href="#">Yardım Sitesi</a>
	    </div>
	    <div class="collapse navbar-collapse" id="myNavbar">
	      	<ul class="nav navbar-nav navbar-right">
       			<li class="dropdown">
			        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i> &nbsp;Kullanici Adi <span class="caret"></span></a>
			        <ul class="dropdown-menu">
				        <li><a href="profilim.html">Profilim</a></li>
				        <li role="separator" class="divider"></li>
				        <li><a href="#">Çıkış</a></li>
			        </ul>
			    </li>
     		</ul>
		</div>
	  </div>
	</nav>

	<!-- main tasarım -->
	<div class="container-fluid">
		<div class="col-md-12">
			<div class="jumbotron">
			<div class="row">
				<div class="col-md-4"><button type="button" class="btn btn-success btn-lg btn-block" data-toggle="modal" data-target="#hikaye_ekle">Hikayemi Ekle</button></div>
				<div class="col-md-4"><button type="button" class="btn btn-info btn-lg btn-block" data-toggle="modal" data-target="#rezerve">Rezerve Ettiklerim</button></div>
				<div class="col-md-4"><button type="button" class="btn btn-warning btn-lg btn-block" data-toggle="modal" data-target="#teslim">Teslim Aldıklarım</button></div>
			</div><br>
				
				<br>
					<div id="hikaye_ekle" class="modal fade" role="dialog">
					  <div class="modal-dialog">

					    <!-- Modal content-->
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal">&times;</button>
					        <h4 class="modal-title"><b style="color: #5CB85C;">Hikayemi Ekle</b></h4>
					      </div>
					      <div class="modal-body">
					       <form>
					       <label for="exampleInputEmail1" style="color: #5CB85C;">Hikaye Başlığı:</label>
					      <input type="text" class="form-control">
					       	<label for="exampleInputEmail1" style="color: #5CB85C;">Hikayem</label>
					      	<textarea class="form-control" rows="3"></textarea><br>
					       
					      </div>
					      <div class="modal-footer">
					      <button type="submit" class="btn btn-success">Kaydet</button></form>
					        <button type="button" class="btn btn-default" data-dismiss="modal">Kapat</button>

					      </div>
					    </div>

					  </div>
					</div>

					<div id="rezerve" class="modal fade" role="dialog">
					  <div class="modal-dialog">

					    <!-- Modal content-->
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal">&times;</button>
					        <h4 class="modal-title"><b style="color: #5BC0DE;">Rezerve Ettiklerim</b></h4>
					      </div>
					      <div class="modal-body">
					     		<p>Malzeme Başlığı</p><hr>
					     		<p>Malzeme Başlığı</p><hr>
					     		<p>Malzeme Başlığı</p><hr>
					     		<p>Malzeme Başlığı</p><hr>
					     		<p>Malzeme Başlığı</p>
							  
					      </div>
					      <div class="modal-footer">
							<button type="button" class="btn btn-default" data-dismiss="modal">Kapat</button>
					      </div>
					    </div>

					  </div>
					</div>

					<div id="teslim" class="modal fade" role="dialog">
					  <div class="modal-dialog">

					    <!-- Modal content-->
					    <div class="modal-content">
					      <div class="modal-header">
					        <button type="button" class="close" data-dismiss="modal">&times;</button>
					        <h4 class="modal-title"><b style="color: #F0AD4E;">Malzemelerim</b></h4>
					      </div>
					      <div class="modal-body">
					        <p>Teslim Aldıklarım</p><hr>
					     	<p>Teslim Aldıklarım</p><hr>
					     	<p>Teslim Aldıklarım</p><hr>
					     	<p>Teslim Aldıklarım</p><hr>
					     	<p>Teslim Aldıklarım</p><hr>
					     	<p>Teslim Aldıklarım</p>
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-default" data-dismiss="modal">Kapat</button>
					      </div>
					    </div>

					  </div>
					</div>
		
					<div class="row">
						<div class="col-md-3">
					      <a href="#" class="thumbnail" data-toggle='tooltip' data-placement='bottom' title='Buraya Açıklama Yazısı Eklenecektir.!'>
					        <p>Malzeme Başlığı</p> 
					        <img src="http://lorempixel.com/image_output/abstract-q-c-640-480-8.jpg" alt="Pulpit Rock" style="width:230px;height:230px"><br>
					        <button type="button" class="btn btn-primary active btn-block">Rezerve Et</button> 
					      </a>
					    </div>
					    <div class="col-md-3">
					      <a href="#" class="thumbnail" data-toggle='tooltip' data-placement='bottom' title='Buraya Açıklama Yazısı Eklenecektir.!'>
					        <p>Malzeme Başlığı</p>   
					        <img src="http://lorempixel.com/image_output/food-q-c-640-480-7.jpg" alt="Pulpit Rock" style="width:230px;height:230px"><br>
					        	<button type="button" class="btn btn-primary disabled btn-block">Rezerve Edildi</button>
					      </a>
					    </div>
					    <div class="col-md-3">
					      <a href="#" class="thumbnail" data-toggle='tooltip' data-placement='bottom' title='Buraya Açıklama Yazısı Eklenecektir.!'>
					        <p>Malzeme Başlığı</p>   
					        <img src="http://lorempixel.com/image_output/food-q-c-640-480-5.jpg" alt="Pulpit Rock" style="width:230px;height:230px"> 
					        <br><button type="button" class="btn btn-primary active btn-block">Rezerve Et</button>
					      </a>
					    </div>
					    <div class="col-md-3">
					      <a href="#" class="thumbnail" data-toggle='tooltip' data-placement='bottom' title='Buraya Açıklama Yazısı Eklenecektir.!'>
					        <p>Malzeme Başlığı</p>   
					        <img src="http://lorempixel.com/image_output/nightlife-q-c-640-480-9.jpg" alt="Pulpit Rock" style="width:230px;height:230px"><br>
					          <button type="button" class="btn btn-primary disabled btn-block">Rezerve Edildi</button>
					      </a>
					    </div>

					    <!--Burada döngü başlıyor döngüye sokarsın -->
							<div class="col-md-3">
					      <a href="#" class="thumbnail" data-toggle='tooltip' data-placement='bottom' title='Buraya Açıklama Yazısı Eklenecektir.!'>
					        <p>Malzeme Başlığı</p> 
					        <img src="http://lorempixel.com/image_output/abstract-q-c-640-480-8.jpg" alt="Pulpit Rock" style="width:230px;height:230px"><br>
					        <button type="button" class="btn btn-primary active btn-block">Rezerve Et</button> 
					      </a>
					    </div>
					    <div class="col-md-3">
					      <a href="#" class="thumbnail" data-toggle='tooltip' data-placement='bottom' title='Buraya Açıklama Yazısı Eklenecektir.!'>
					        <p>Malzeme Başlığı</p>   
					        <img src="http://lorempixel.com/image_output/food-q-c-640-480-7.jpg" alt="Pulpit Rock" style="width:230px;height:230px"><br>
					        	<button type="button" class="btn btn-primary disabled btn-block">Rezerve Edildi</button>
					      </a>
					    </div>
					    <div class="col-md-3">
					      <a href="#" class="thumbnail" data-toggle='tooltip' data-placement='bottom' title='Buraya Açıklama Yazısı Eklenecektir.!'>
					        <p>Malzeme Başlığı</p>   
					        <img src="http://lorempixel.com/image_output/food-q-c-640-480-5.jpg" alt="Pulpit Rock" style="width:230px;height:230px"> 
					        <br><button type="button" class="btn btn-primary active btn-block">Rezerve Et</button>
					      </a>
					    </div>
					    <div class="col-md-3">
					      <a href="#" class="thumbnail" data-toggle='tooltip' data-placement='bottom' title='Buraya Açıklama Yazısı Eklenecektir.!'>
					        <p>Malzeme Başlığı</p>   
					        <img src="http://lorempixel.com/image_output/nightlife-q-c-640-480-9.jpg" alt="Pulpit Rock" style="width:230px;height:230px"><br>
					          <button type="button" class="btn btn-primary disabled btn-block">Rezerve Edildi</button>
					      </a>
					    </div>
					</div>
					
			</div>
		</div>
		
	</div>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>
</body>
</html>

templates/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% crispy form %}
{% endblock %}

templates/post_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    {% crispy form %}

{% endblock %}